name: funny_monster
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  # Service locator
  get_it: ^7.6.0
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.6
  # Local cache
  shared_preferences: ^2.1.1
  # Animate any widget
  show_up_animation: ^2.0.0
  dotted_border: ^2.0.0+3
  font_awesome_flutter: ^10.5.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/



  fonts:
    - family: AveriaLibreBold
      fonts:
        - asset: assets/fonts/AveriaLibre-Bold.ttf

    - family: AveriaLibreRegular
      fonts:
        - asset: assets/fonts/AveriaLibre-Regular.ttf

    - family: GilroyMediumItalic
      fonts:
        - asset: assets/fonts/Gilroy-MediumItalic.otf


    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.otf



    - family: PaytoneOneRegular
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf